[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.chromadb"

[deploy]
startCommand = "chroma run --host 0.0.0.0 --port $PORT --path /data/chroma"
healthcheckPath = "/api/v1/heartbeat"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[[volumes]]
name = "chroma-data"
mountPath = "/data/chroma" 