[build]
builder = "nixpacks"
buildCommand = "pip install -r railway_requirements.txt"

[deploy]
startCommand = "uvicorn singleModel:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyMaxRetries = 10 